apiVersion: v1
kind: Namespace
metadata:
  name: unipay

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unipay-auth-depl
  namespace: unipay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unipay-auth
  template:
    metadata:
      labels:
        app: unipay-auth
    spec:
      containers:
        - name: unipay-auth
          image: docker.pkg.github.com/poscloudzw/unipay-auth/unipay-auth-service
      imagePullSecrets:
        - name: munyaregcred

---
apiVersion: v1
kind: Service
metadata:
  name: unipay-auth-clusterip-srv
  namespace: unipay
spec:
  selector:
    app: unipay-auth
  ports:
    - name: unipay-auth
      protocol: TCP
      port: 9001
      targetPort: 9001
